# Generated by Django 3.1 on 2021-03-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listanimal', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorit_animal',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='listanimal.AnimalInfo'),
        ),
    ]
