# Generated by Django 3.1 on 2021-03-17 17:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_news', models.URLField()),
                ('description_news', models.TextField()),
                ('heading', models.TextField()),
                ('main_text', models.TextField(null=True)),
                ('url_media', models.URLField(blank=True, null=True)),
                ('time_post', models.CharField(max_length=100)),
                ('gallery_img', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewestLogFileContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_filename', models.CharField(max_length=200, verbose_name='название файла логера')),
                ('content', models.TextField(null=True, verbose_name='Запись файла')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Последние записи логов по файлам',
                'verbose_name_plural': 'Последние записи логов по файлам',
            },
        ),
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), size=None)),
                ('animal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='listanimal.animaltype')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='listanimal.animalcolor')),
            ],
        ),
    ]
